version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - helpdesk-net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  rabbitmq:
    container_name: rabbitmq_broker
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - helpdesk-net

networks:
  helpdesk-net:
    driver: bridge

volumes:
  pgdata:
    external: true
  pgadmin:
    external: true
