version: '3'

services:
  software_backend_api:
    container_name: software_backend_api
    image: software_backend_api:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    networks:
      - software-api-net
    depends_on:
      - 'rabbitmq'
      - 'postgres'
      - 'minio'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - software-api-net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq_broker
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - software-api-net
    restart: unless-stopped

  minio:
    image: minio/minio
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    networks:
      - software-api-net
    restart: unless-stopped

networks:
  software-api-net:
    driver: bridge

volumes:
  pgdata:
    external: true
  pgadmin:
    external: true
  minio_storage:
    external: true
